Department fe view
DANIDIA/library_system_frontend pull request #26
Opened 2024-05-18 20:00 UTC by DANIDIA

2024-05-18 21:32 UTC, RomanovYurii requested changes

2024-05-18 21:32 UTC, RomanovYurii commented on src/layouts/PanelLayout/PanelRouter.js
> +            <Route path='creation' element={<DepartmentCreationView />} />
If you already created several `*Paths` constants, why didn't you create such here?

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentBaseView/DepartmentBaseView.js
> +            <button onClick={() => navigate('creation')}>
Use constants, instead of inline declaration (for the path)

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentBaseView/DepartmentBaseView.js
> +export function DepartmentBaseView() {
Sorry, I am starting to forget the meaning of the word "base"... You use it everywhere, meaning everything by it...
Please, do refactor 🙏

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/components/DepartmentFormView/DepartmentFormView.js
> +    startValues = {},
`initialValues`

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentCreationView/DepartmentCreationView.js
> +                buttonText='create'
Just take a second and imagine how this line looks like for someone, besides you.
You are trying to specify params of some form. And the only two things that exist there are properties of some magic *button*... What is that button? Why is it specified here?

It should be clear from the name of the parameter what value should someone put there.

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentCreationView/DepartmentCreationView.js
> +    const handleCreation = () => {};
I don't really see the reason to have the placeholder functions like this. Just don't pass anything, if it is not ready

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageEditView/DepartmentPageEditView.js
> +    const hasUserPermission =
Why `...User...` permission? Maybe `hasDepartmentEditPermission`?

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageView/DepartmentPageView.js
> +            {outlet ? (
Please, learn how `||` and `??` work in JS and React.

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentSearchView/DepartmentSearchView.js
> +                buttonClickHandler={handleSearch()}
```suggestion
                buttonClickHandler={handleSearch}
```

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/components/DepartmentFormView/DepartmentFormView.js
> +        const formData = { name, address, contactNumber };
You don't need a constant declaration here

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentBaseView/DepartmentBaseView.js
> +export function DepartmentBaseView() {
`DepartmentIndexView`, `DepartmentDefaultView` etc

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageEditView/DepartmentPageEditView.js
> +export function DepartmentPageEditView() {
It's either `Page` or `View`, don't mix these up

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageView/DepartmentPageView.js
> +export function DepartmentPageView() {
Same, it's either `Page` or `View`, don't mix these up

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageEditView/DepartmentPageEditView.js
> +import React from 'react';
Two imports from `react`? It should be reduced to one line

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentSearchView/DepartmentSearchView.js
> +export function DepartmentSearchView() {
This is not specifically search view. First of all, this is `List` view, and only then it's `Search` view

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/components/DepartmentFormView/DepartmentFormView.js
> +                    type='text'
Not `type="text"`

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentSearchView/DepartmentSearchView.js
> +                    <tr onClick={() => navigation('../page/1')}>
What is `../page/1`?

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentSearchView/DepartmentSearchView.js
> +    const navigation = useNavigate();
Why do you have `navigation` here, while everywhere else you call it `navigate` and even a hook is called `useNavigate`?

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageView/DepartmentPageView.js
> +                    ) : userRole === roles.ADMIN ? (
To be honest, this chaining doesn't really appeal to me. I prefer when it's declared per row, like
```
{userRole === roles.ADMIN && (...)}
{userRole === roles.DEPARTMENT_MANAGER && (...)}
```

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageView/DepartmentPageView.js
> +    const userRole = userData.role;
When you'll have time, learn what `useMemo` and `useCallback` hooks do. For now, it is enough, that this just works

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageView/DepartmentPageView.js
> +    const outlet = useOutlet();
Usually, it is more readable, when hooks are sorted as following:

```
// Self-named hooks
const navigate = useNavigate();
const outlet = useOutlet();

// Properties, params, context and other "ouside"-related hooks
const { departmentID } = useParams();
const { userData } = useContext(SessionContext);

// State hooks
const [departmentData, setDepartmentData] = useState();
```

2024-05-18 21:32 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentCreationView/DepartmentCreationView.js
> +                buttonText='create'
E.g. `submitButtonHandler`

2024-05-18 21:33 UTC, RomanovYurii commented on src/layouts/PanelLayout/PanelRouter.js
> +            <Route path='creation' element={<DepartmentCreationView />} />
`departmentsPaths` or `departmentPaths`

2024-05-18 21:35 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageEditView/DepartmentPageEditView.js
> +export function DepartmentPageEditView() {
`DepartmentEditView`

2024-05-18 21:35 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentPageView/DepartmentPageView.js
> +export function DepartmentPageView() {
`DepartmentSingleView` or `DepartmentDetailsView`

2024-05-18 21:36 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentSearchView/DepartmentSearchView.js
> +export function DepartmentSearchView() {
`DepartmentsListView`

2024-05-18 21:36 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/components/DepartmentFormView/DepartmentFormView.js
> +                    type='text'
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

2024-05-18 21:38 UTC, RomanovYurii commented
Working on a task related to "visuals" only, don't forget that even for this purpose you are writing a code - it still should be working, clean and readable 😉

2024-05-20 13:48 UTC, DANIDIA commented on src/views/PanelViews/DepartmentViews/DepartmentSearchView/DepartmentSearchView.js
> +                    <tr onClick={() => navigation('../page/1')}>
It is needed only for redirection on `DepartmentPageView `and testing it. In next PR it will be replaced

2024-05-20 14:09 UTC, DANIDIA commented on src/views/PanelViews/DepartmentViews/DepartmentBaseView/DepartmentBaseView.js
> +export function DepartmentBaseView() {
I think a good substitution of word **'base'** can be word **'hub'**: `DepartmentHubView`, 'HubPaths', `ManagerHubView`(in future)

2024-05-20 15:12 UTC, RomanovYurii commented on src/views/PanelViews/DepartmentViews/DepartmentBaseView/DepartmentBaseView.js
> +export function DepartmentBaseView() {
Why `Hub`? I mean, this is default or initial view, hub means "gathering" something... Or at least `basic`... To be honest, I have never seen `Base` or `Hub` naming in real projects 🤔

2024-05-20 17:42 UTC, DANIDIA commented on src/views/PanelViews/DepartmentViews/DepartmentBaseView/DepartmentBaseView.js
> +export function DepartmentBaseView() {
Oh, when I use `DepartmentBaseView` i mean 'View of base of department'. Ok, it definitely should be renamed :D . `panel`  can be better option

2024-05-21 16:44 UTC, RomanovYurii approved these changes

2024-05-22 09:49 UTC, merged